/*
  # Populate vocabulary database with initial data

  This migration adds a comprehensive set of vocabulary words with:
  - Complete definitions and usage examples
  - Etymology and root information
  - Synonyms and antonyms
  - Quotes and tenses where applicable
  - Varied difficulty levels
*/

-- Populate words table with initial vocabulary data
INSERT INTO words (word, part_of_speech, meaning, usage, synonyms, antonyms, etymology, root_info, past_tense, present_tense, future_tense, quote, difficulty) 
VALUES
  (
    'ephemeral',
    'adjective',
    'Lasting for a very short time; transitory',
    'The ephemeral beauty of cherry blossoms makes them all the more precious.',
    ARRAY['fleeting', 'transient', 'momentary', 'evanescent', 'short-lived'],
    ARRAY['permanent', 'eternal', 'everlasting', 'perpetual', 'enduring'],
    'From Greek ephēmeros, meaning "lasting only one day": epi- ("on") + hēmera ("day")',
    'epi- (upon, on) + hemera (day)',
    NULL,
    NULL,
    NULL,
    'Beauty is ephemeral, but a beautiful memory can last forever.',
    'advanced'
  ),
  (
    'serendipity',
    'noun',
    'The occurrence and development of events by chance in a happy or beneficial way',
    'Finding his dream job while looking for something else was pure serendipity.',
    ARRAY['chance', 'fortuity', 'fortune', 'luck', 'providence'],
    ARRAY['misfortune', 'design', 'plan', 'calculation', 'intention'],
    'Coined by Horace Walpole in 1754 after the Persian fairy tale "The Three Princes of Serendip"',
    'From Serendip, an old Persian name for Sri Lanka',
    NULL,
    NULL,
    NULL,
    'In science, serendipity is not a method, but it is a moment that a prepared mind can recognize and use.',
    'advanced'
  ),
  (
    'ameliorate',
    'verb',
    'To make something bad or unsatisfactory better',
    'The new policies were designed to ameliorate the living conditions of the poor.',
    ARRAY['improve', 'enhance', 'upgrade', 'better', 'reform'],
    ARRAY['worsen', 'aggravate', 'deteriorate', 'degrade', 'exacerbate'],
    'From French améliorer, from Latin melior meaning "better"',
    'melior- (better)',
    'ameliorated',
    'ameliorates',
    'will ameliorate',
    'Education is the most powerful weapon which you can use to ameliorate the world.',
    'advanced'
  ),
  (
    'ubiquitous',
    'adjective',
    'Present, appearing, or found everywhere',
    'Smartphones have become ubiquitous in modern society.',
    ARRAY['omnipresent', 'universal', 'pervasive', 'worldwide', 'global'],
    ARRAY['rare', 'scarce', 'limited', 'restricted', 'uncommon'],
    'From Latin ubique meaning "everywhere"',
    'ubique (everywhere)',
    NULL,
    NULL,
    NULL,
    'Technology is becoming as ubiquitous as the air we breathe.',
    'advanced'
  ),
  (
    'perspicacious',
    'adjective',
    'Having a ready insight into and understanding of things',
    'Her perspicacious analysis of the situation impressed everyone in the room.',
    ARRAY['perceptive', 'astute', 'insightful', 'discerning', 'shrewd'],
    ARRAY['unperceptive', 'obtuse', 'undiscerning', 'imperceptive', 'blind'],
    'From Latin perspicax, from perspicere "to look through, see clearly"',
    'per- (through) + specere (to look)',
    NULL,
    NULL,
    NULL,
    'The perspicacious reader will have already guessed the ending.',
    'advanced'
  ),
  (
    'eloquent',
    'adjective',
    'Fluent or persuasive in speaking or writing',
    'She gave an eloquent speech that moved the audience to tears.',
    ARRAY['articulate', 'expressive', 'fluent', 'persuasive', 'silver-tongued'],
    ARRAY['inarticulate', 'awkward', 'halting', 'stammering', 'tongue-tied'],
    'From Latin eloquens, present participle of eloqui: "to speak out"',
    'e- (out) + loqui (to speak)',
    NULL,
    NULL,
    NULL,
    'True eloquence consists in saying all that is necessary, and nothing but what is necessary.',
    'intermediate'
  ),
  (
    'resilient',
    'adjective',
    'Able to withstand or recover quickly from difficult conditions',
    'The resilient community quickly rebuilt after the natural disaster.',
    ARRAY['tough', 'adaptable', 'flexible', 'hardy', 'buoyant'],
    ARRAY['fragile', 'weak', 'vulnerable', 'delicate', 'frail'],
    'From Latin resiliens, present participle of resilire "to spring back"',
    're- (back) + salire (to jump, leap)',
    NULL,
    NULL,
    NULL,
    'The human spirit is resilient. No matter how many times it is broken, it will fight to survive.',
    'intermediate'
  ),
  (
    'pragmatic',
    'adjective',
    'Dealing with things sensibly and realistically in a way that is based on practical considerations',
    'We need a pragmatic approach to solving this problem.',
    ARRAY['practical', 'realistic', 'sensible', 'rational', 'reasonable'],
    ARRAY['idealistic', 'unrealistic', 'impractical', 'theoretical', 'visionary'],
    'From Greek pragmatikos, from pragma "deed"',
    'pragma (deed, action)',
    NULL,
    NULL,
    NULL,
    'A pragmatic leader focuses on results rather than ideology.',
    'intermediate'
  ),
  (
    'benevolent',
    'adjective',
    'Kind, generous, and caring about others',
    'The benevolent donor provided funds for the new children''s hospital.',
    ARRAY['kind', 'generous', 'charitable', 'altruistic', 'philanthropic'],
    ARRAY['malevolent', 'cruel', 'unkind', 'harsh', 'hostile'],
    'From Latin bene (well) + volens (wishing)',
    'bene- (good, well) + volens (wishing)',
    NULL,
    NULL,
    NULL,
    'A benevolent heart is like a garden where kindness grows.',
    'intermediate'
  ),
  (
    'diligent',
    'adjective',
    'Having or showing care and conscientiousness in one''s work or duties',
    'Her diligent study habits resulted in excellent grades.',
    ARRAY['hardworking', 'industrious', 'conscientious', 'assiduous', 'meticulous'],
    ARRAY['lazy', 'negligent', 'careless', 'slack', 'indolent'],
    'From Latin diligens, present participle of diligere "to value highly, take delight in"',
    'di- (apart) + legere (to choose, select)',
    NULL,
    NULL,
    NULL,
    'Success is the sum of small efforts, repeated day in and day out by diligent workers.',
    'beginner'
  ),
  (
    'persevere',
    'verb',
    'Continue in a course of action despite difficulty or lack of success',
    'Despite numerous setbacks, she persevered with her research.',
    ARRAY['persist', 'continue', 'endure', 'prevail', 'maintain'],
    ARRAY['quit', 'surrender', 'yield', 'abandon', 'give up'],
    'From Latin perseverare "to persist, persevere"',
    'per- (through) + severus (serious)',
    'persevered',
    'perseveres',
    'will persevere',
    'Those who persevere in the face of adversity are the ones who achieve greatness.',
    'beginner'
  ),
  (
    'authentic',
    'adjective',
    'Of undisputed origin and not a copy; genuine',
    'The museum displayed authentic artifacts from ancient Egypt.',
    ARRAY['genuine', 'real', 'legitimate', 'original', 'true'],
    ARRAY['fake', 'counterfeit', 'artificial', 'imitation', 'bogus'],
    'From Greek authentikos "original, genuine, principal"',
    'autos (self) + hentes (doer, being)',
    NULL,
    NULL,
    NULL,
    'To be authentic in a world of copies is the greatest achievement.',
    'beginner'
  ),
  (
    'innovative',
    'adjective',
    'Featuring new methods; advanced and original',
    'The company is known for its innovative approach to problem-solving.',
    ARRAY['creative', 'original', 'groundbreaking', 'pioneering', 'inventive'],
    ARRAY['conventional', 'traditional', 'old-fashioned', 'conservative', 'standard'],
    'From Latin innovatus, past participle of innovare "to renew, restore"',
    'in- (into) + novus (new)',
    NULL,
    NULL,
    NULL,
    'Innovation distinguishes between a leader and a follower.',
    'beginner'
  ),
  (
    'tenacious',
    'adjective',
    'Tending to keep a firm hold of something; persistent',
    'Her tenacious pursuit of justice finally paid off.',
    ARRAY['persistent', 'determined', 'resolute', 'steadfast', 'dogged'],
    ARRAY['irresolute', 'weak', 'yielding', 'irresolute', 'wavering'],
    'From Latin tenax "holding fast"',
    'tenere (to hold)',
    NULL,
    NULL,
    NULL,
    'It''s not that I''m so smart, it''s just that I stay with problems longer - a testament to tenacious thinking.',
    'beginner'
  ),
  (
    'empathy',
    'noun',
    'The ability to understand and share the feelings of another',
    'Her empathy for the patients made her an excellent nurse.',
    ARRAY['compassion', 'sympathy', 'understanding', 'sensitivity', 'rapport'],
    ARRAY['indifference', 'apathy', 'coldness', 'detachment', 'insensitivity'],
    'From Greek empatheia, from en- "in" + pathos "feeling"',
    'en- (in) + pathos (feeling)',
    NULL,
    NULL,
    NULL,
    'Empathy is seeing with the eyes of another, listening with the ears of another, and feeling with the heart of another.',
    'beginner'
  );